name: midterm_project
description: A new Flutter project.

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  animated_text_kit: ^4.2.2
  provider: ^6.0.5

  cupertino_icons: ^1.0.5
  shrine_images: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  # TODO: Insert Fonts (103)
  uses-material-design: true
  assets:
    - assets/diamond.png
    - assets/polonia.jpg
    - assets/hilton.jpg
    - assets/berlin.png
    - assets/marina.png
    - assets/carlton.jpg
    - assets/regis.jpg